### ISSUE TITLE
Code has not been pushed from Driver Station.

### ISSUE THREAD

**Issue by Naqu6** [team8/pneumatic-rally-bot#3]
The Code on the Dev branch is not current. We should update git  ASAP.

**Comment by rselwyn** [comment]
We were having issues connecting the laptop to the internet to run a `git push`.  All the changes have been committed.

**Comment by Naqu6** [comment]
Robbie, the issues are because the Wifi is configured to connect to the
robot.

I will show you how to fix this next time I see you.

On Sun, Nov 15, 2015 at 7:39 PM, Robbie S <notifications@github.com> wrote:

> Closed #3 <https://github.com/team8/pneumatic-rally-bot/issues/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team8/pneumatic-rally-bot/issues/3#event-465007086>.
>



--

**Comment by Naqu6** [comment]
To fix the problem, go to control panel,  click on etherner/wifi in the network and sharing center.
Click on properties, then the fourth option which contains the word ipv4. Change the option that says automatically obtain ip. Save the settings.
